### ISSUE TITLE
use this in aldryn-bootstrap3 

### ISSUE THREAD

**Issue by matzegebbe** [divio/djangocms-attributes-field#13]
is it possible to use this plugin with aldryn_bootstrap3? 

i edit

https://github.com/aldryn/aldryn-bootstrap3/blob/master/aldryn_bootstrap3/models.py

```
lib/python2.7/site-packages/aldryn_bootstrap3/models.py
```

but I do not get it to run :( or is this the wrong place?

thanks!

**Comment by FinalAngel** [comment]
@matzegebbe please open an Issue or PR in https://github.com/aldryn/aldryn-bootstrap3. You can implement it very easy, a working example: 

1. https://github.com/divio/djangocms-link/blob/master/djangocms_link/models.py#L16
2. https://github.com/divio/djangocms-link/blob/master/djangocms_link/models.py#L105
3. https://github.com/divio/djangocms-link/blob/master/setup.py#L10
