### ISSUE TITLE
flatatt has moved to django.forms.utils

### ISSUE THREAD

**Issue by oliwarner** [divio/djangocms-attributes-field#20]
Currently testing on Django 1.11rc1 and I'm getting:

    ImportError: cannot import name 'flatatt'

This is caused by an import in your `widgets.py`:

    from django.forms.widgets import flatatt

It should be safe enough to change this to 

    from django.forms.utils import flatatt

This is what ever other package using flatatt directly seems to do but you'll still want to pass it through tox.

**Comment by FinalAngel** [comment]
@oliwarner thanks for the report, we will keep that in mind once 1.11 releases.

**Comment by FinalAngel** [comment]
https://github.com/divio/djangocms-link/issues/124 duplicate

**Comment by susahe** [comment]
wow i change 
from django.forms.widgets import flatatt

It should be safe enough to change this to

from django.forms.utils import flatatt
its work for me thanks

**Comment by vstoykov** [comment]
This should be fixed by #22

**Comment by careercoder** [comment]
What's the lastest? Fix for DRF?

**Comment by FinalAngel** [comment]
This has been released :)
