### ISSUE TITLE
key:value pairs not saved to database

### ISSUE THREAD

**Issue by russmo** [divio/djangocms-attributes-field#21]
I am using djangocms-attributes-field in both aldryn-bootstrap3 as well as a custom django-cms plugin app that I created.  I just noticed that in either app when adding or editing attribute fields that nothing is saved to the database field.  I'm using postgresql with Django 1.10.6.  I've tested both djangocms-attributes-field version 0.2.0 and 0.1.2 and get the same problem.

After entering key/value pairs in the widget, I save the plugin instance.  All of the other fields are updated in the database, but the attributes field remains an empty set '{}'.  If I edit the attributes field directly in the database and enter a json dict with the key/values, then they appear in the plugin editing widget.  If I subsequently edit those in the widget and save, the values are unchanged in the db.

Any clues on what I might be doing wrong, or is this something that others notice?

Best regards,
Russmo

**Comment by FinalAngel** [comment]
@russmo thanks for the report, it might be cause of Django 1.10, are you able to reproduce this on 1.8? @divio/django-cms-core what do you guys think?

**Comment by haricot** [comment]
For more info, the attributes works with django 1.8 and 1.9 but not with django 1.10.

**Comment by wservices** [comment]
That it works for Django 1.10 add the following lines in the file widgets.py (class AttributesWidget):
    def value_omitted_from_data(self, data, files, name):
        return False

**Comment by FinalAngel** [comment]
@haricot or @wservices anyone able to propose a pull request? :)

**Comment by haricot** [comment]
@wservices  Many thanks :) 
@FinalAngel  Yes  with pleasure !
