### ISSUE TITLE
Maybe I'm missing something...

### ISSUE THREAD

**Issue by ursomniac** [divio/djangocms-attributes-field#25]
So I've added an AttributesField to one of my plugin models.
It appears in the Admin when I go to add an instance of the plugin.
However, after I add attributes, and click Save, they don't get stored.  (Just {} in the database).

I've noticed this is also happening with the generic Django CMS plugins (Filer, Picture, etc.).
Is there some setup step that I'm neglecting?

The site is using 
Django==1.10.7
djangocms-attributes-field == 0.1.2
django-cms == 3.4.4

**Comment by mihalikv** [comment]
probably you have this problem 

https://github.com/divio/djangocms-attributes-field/commit/982d0a0b8343bbeb6ae1c07402821361386e4258

Try to upgrade djangocms-attributes-field

**Comment by ursomniac** [comment]
Nope - version 0.3.0 still has the same issues.   Isn't this the fundamental purpose of the app?
