### ISSUE TITLE
ValueError loading fixtures: not enough values to unpack (expected 2, got 0)

### ISSUE THREAD

**Issue by marcosguedes** [divio/djangocms-attributes-field#37]
Hi there! Not sure if this issue belongs to [djangocms-picture](https://github.com/divio/djangocms-picture/) where I've encountered this error but since its happening on [fields.py, line 222](https://github.com/divio/djangocms-attributes-field/blob/1.2.0/djangocms_attributes_field/fields.py#L222), I guess this might be the best place to report it.

When dumping the page and plugin into a fixture and loading them again, the page breaks on access.

The command I used was roughly `python manage.py dumpdata auth.user cms cms.cmsplugin filer djangocms_picture --natural-foreign --indent=4 --format=xml > fixtures/initial_data.xml` and to load it was `python manage.py loaddata fixtures/initial_data.xml`

Python: 3.6.9
Django: 2.2
CMS: 3.7.1
djangocms-attributes-field: 1.2.0

I can try to conjure up a simple test project later today if it helps. Thanks for looking into this

**Comment by FinalAngel** [comment]
thank you @marcosguedes, please reopen in djangocms-picture if this is still relevant :)
