### ISSUE TITLE
TypeError: Expected string or buffer with postgres 9.4 / Django 1.9 / psycopg2 2.5.4

### ISSUE THREAD

**Issue by yakky** [divio/djangocms-attributes-field#7]
jsonfield is created as jsonb datatype in postgres 9.4 / Django 1.9 and psycopg2 2.5.4 automatically converts jsonb data to python object automatically when reading from the database, resulting in "TypeError: Expected string or buffer" exception.
Upstream error is https://bitbucket.org/schinckel/django-jsonfield/pull-requests/32/make-from_db_value-compatible-with/

Probably a mitigation technique can be applied in this package

Workaround to overcome the issue is to use pyscopg2 < 2.5.4 

Linked to #6 and #8

**Comment by yakky** [comment]
Fixed by #8

**Comment by stephendwolff** [comment]
unfortunately i think this fix broke things for MySQL
